stage('Deploy Microservice') {
    steps {
        script {
            echo "Starting deployment for Employee Service..."
            deployer.validate(params.ENVIRONMENT)

            // --- ADD THIS LINE ---
            error "Simulating a deployment failure for rollback test!"
            // ---------------------

            deployApp(params.ENVIRONMENT)
        }
    }
}
